services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - default
  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    volumes:
      - es-pgdata:/var/lib/postgresql/data
    # Contains POSTGRES_PASSWORD required to initialize the database
    env_file:
      - .env
    networks:
      - default
volumes:
  es-pgdata:
networks:
  default:
    external: false
