services:
  app:
    container_name: es-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db-proxy
    env_file:
      - .env
  db:
    container_name: es-db
    image: postgres:16.4
    ports:
      - "5432:5432"
    volumes:
      - es-pgdata:/var/lib/postgresql/data
    # Contains POSTGRES_PASSWORD required to initialize the database
    # If you initially run the database without this file, you will need to remove the volume to reset the password.
    env_file:
      - .env
  db-proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    container_name: es-db-proxy
    environment:
      APPEND_PORT: "db:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
      LOG_CONN_INFO: "true"
    ports:
      - "54321:80"
    depends_on:
      - db

volumes:
  es-pgdata:
